### ISSUE TITLE
import.meta.url, and import.meta generally

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-reviews#208]
Dear Sirs and Madam of TAG!

Another ECMAScript/web platform-spanning review for you all.

  - Name: import.meta, with specific focus on import.meta.url
  - Specification URL:
    - JavaScript-side spec (import.meta in general): https://tc39.github.io/proposal-import-meta/
    - HTML-side spec (import.meta.url): https://github.com/whatwg/html/pull/3141
  - Explainer, Requirements Doc, or Example code:
    - https://github.com/tc39/proposal-import-meta/blob/master/README.md
    - May also be interesting: [presentation](https://docs.google.com/presentation/d/1p1BGFY05-iCiop8yV0hNyWU41_wlwwfv6HIDkRNNIBQ/edit?usp=sharing) that helped originate this feature
  - Tests: https://github.com/w3c/web-platform-tests/pull/7888
  - Primary contacts: @domenic, @gsathya, @hiroshige-g

Further details (optional):

  - Relevant time constraints or deadlines: we plan to ship this in Chrome 63, which branches in mid October and ships in early December
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The assessment is no to all/no difference in incognito mode.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

This design went through a lot of discussion at TC39 as to the exact syntax for exposing per-module metadata. You can find some [minutes](https://github.com/tc39/tc39-notes/blob/master/es8/2017-05/may-23.md#16iiia-accessing-host-specific-module-metadata-from-inside-a-module) discussing the above-linked presentation if you are curious as to how the specific choices here were arrived at.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue

If the TAG is interested, we're currently trying to figure out how to add a second import.meta property, import.meta.scriptElement, but it is a bit tricky. Feel free to help us out at whatwg/html#1013; the trouble starts around https://github.com/whatwg/html/issues/1013#issuecomment-329344476 .

**Comment by torgo** [comment]
We discussed on today's call. @slightlyoff to write some feedback.

**Comment by slightlyoff** [comment]
Wow, sorry for leaving this so long.

I note that this has probably shipped: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Hq3cVNto74c

In general, the feature looks hugely useful. My only concern is about naming collisions. Given that names are added by host environments, it would seem best if there were a central registry.

**Comment by annevk** [comment]
Per https://tc39.github.io/proposal-import-meta/ the host (of which there's always one) supplies all the values, so by definition whoever implements HostGetImportMetaProperties (HTML Standard in case of the web platform) will define the registry.

**Comment by mko-io** [comment]
what about import.meta.currentElement?

**Comment by slightlyoff** [comment]
@annevk: HTML having a unique registry (not shared, ala IANA) is exactly the problem I was trying to raise. Happy to see this ship, but would like to see the registry situation end up in a more centralized place across specs and stacks.

**Comment by annevk** [comment]
@slightlyoff fair, I raised https://github.com/tc39/proposal-import-meta/issues/14 to see if some alternate design can be considered that encourages cross-host collaboration.
