### ISSUE TITLE
User Idle Detection

### ISSUE THREAD

**Issue by samuelgoto** [w3ctag/design-reviews#336]
こんにちはTAG！

I'm requesting a TAG review of:

  - Name: User Idle Detection
  - Specification URL: not yet available
  - Explainer, Requirements Doc, or Example code: https://github.com/inexorabletash/idle-detection
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/idle-detection
  - Primary contacts: @samuelgoto, @inexorabletash

Further details (optional):

  - Relevant time constraints or deadlines: [please provide]
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/inexorabletash/idle-detection/blob/master/security-privacy-self-assessment.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

**Comment by slightlyoff** [comment]
Discussed briefly today at the TOK F2F. We weren't able to quickly spot a restriction on access to this API from the top-level frame (and, perhaps, delegation via Feature Policy or `sandbox` attribute). Is that planned?

**Comment by lknik** [comment]
Looks like it may have a potential to profile users, and perhaps potential to misuses with conjunction with other APIs. Has this been been deployed already by any chance (chrome canary?)?

**Comment by cynthia** [comment]
Status here: https://www.chromestatus.com/feature/4590256452009984

**Comment by cynthia** [comment]
@samuelgoto, @inexorabletash do you folks have any feedback on the top-level frame restriction noted above?

**Comment by kenchris** [comment]
- Should this be event based instead of observer based? Check our design principles https://w3ctag.github.io/design-principles/#events-vs-observers
- Should events be delivered to tabs in the background - I think they should, as my Hangouts and Slack tabs are seldom in foreground and people still want to know whether I am idle or not
- Are events restricted to top-frame and https? - they should be
- To reduce multiple sites identifying me as the same person due to the time I idle, it might be possible to introduce some fuzziness between reporting to the various observers
- For IM, users usually want to know if a user is available to know whether they can expect a response or not - but often people in meetings/busy cannot respond - maybe we need a API for sites to report business and these should be tied together

@lknik any more feedback

**Comment by samuelgoto** [comment]
> @samuelgoto, @inexorabletash do you folks have any feedback on the top-level frame restriction noted above?

It sounds like a reasonable restriction to me. @inexorabletash any concerns?

**Comment by inexorabletash** [comment]
sgtm!

**Comment by samuelgoto** [comment]
> Has this been been deployed already by any chance (chrome canary?)?

The feature is still under development and an early version can be accessed in canaries through runtime flags (so no, not available by default).

**Comment by samuelgoto** [comment]
> sgtm!

Ok, I'll update the explainer to make this easier to find and report back on this thread here.

@slightlyoff any other feedback that you think is worth paying attention to?

**Comment by samuelgoto** [comment]
> Ok, I'll update the explainer to make this easier to find and report back on this thread here.

[Done](https://github.com/inexorabletash/idle-detection/commit/f2d319989523e54e80ed53876acb384a1e1a7efd).

**Comment by samuelgoto** [comment]
Great feedback @kenchris ! Let me try to address that!

> Should this be event based instead of observer based? Check our design principles 
> https://w3ctag.github.io/design-principles/#events-vs-observers

Great question and thanks for pointing out that doc!! Super helpful!!! The following seems to be the [general guidance](https://w3ctag.github.io/design-principles/#events-vs-observers):

>> In general, start your design process using an EventTarget and only move to Observers if and when events can’t be made to work well. 

In the specific case of idle detection, I run into the following:

>> Instances observe specific targets, using the observe() and unobserve() methods. The callback provided in the constructor is invoked when something interesting happens to those targets.

In that, in the [EventTarget formulation](https://github.com/samuelgoto/idle-detection/blob/master/README.md#navigatoridlequery), `navigator.idle.query({threshold: 60})` takes a configuration object with a threshold. Does that cross a line to tip us towards observers? Or would are there more precedent for configurations to be passed as the creation of EventTargets?

> Should events be delivered to tabs in the background - I think they should, as my Hangouts and Slack 
> tabs are seldom in foreground and people still want to know whether I am idle or not

Yes, events are delivered to tabs in the background. That's more or less the point of the API, because when your tab is in the foreground, idle detection can be polyfillable (with detecting gestures and the Page Visibility API).

> Are events restricted to top-frame and https? - they should be

[Yes](https://github.com/samuelgoto/idle-detection/commit/f2d319989523e54e80ed53876acb384a1e1a7efd).

> To reduce multiple sites identifying me as the same person due to the time I idle, it might be possible to > introduce some fuzziness between reporting to the various observers

Ah, good point. That came up on a security/privacy review. Let me digest this a bit more and circle back.

> For IM, users usually want to know if a user is available to know whether they can expect a response 
> or not - but often people in meetings/busy cannot respond - maybe we need a API for sites to report 
> business and these should be tied together

Hummmm ... can you walk me through how this would work?

> how important is the configuration? I can easily start a timer myself for say 5 minutes idling before I 
> update my UI, and the event is only send infrequently

The only configuration available is a `threshold` you pass, in seconds, as the criteria for idleness. Without a threshold, you'd have to poll. Does that make sense?

**Comment by domenic** [comment]
> Or would are there more precedent for configurations to be passed as the creation of EventTargets?

There is precedent. Perhaps the most relevant is the generic sensors API: https://w3c.github.io/sensors/

Which also brings up a good point that it seems you could model this with a constructor instead of a navigator.idle() method which returns a non-constructible object.

I might suggest following the generic sensor API as much as possible in naming and usage style. Although probably not by actually subclassing the Sensor class; it seems like you want a subset of that functionality.

**Comment by kenchris** [comment]
Maybe something like (Maybe making threshold not optional to avoid polling?)

```webidl
[SecureContext, Exposed=Window, Constructor(IdleDetectorOptions options)
interface IdleDetector : EventTarget {
  readonly attribute IdleState state;
  readonly attribute DOMHighResTimeStamp? timestamp;
  void start();
  void stop();
  attribute EventHandler onchange;
};

dictionary IdleDetectorOptions {
  double threshold;
};

enum IdleState {
  "active",
  "idle",
  "locked" 
}
```

From your explainer it sounds like "locked" means that screen was turned off, and not a locked screen like WakeLock - those need to be aligned.

If you really need a one-shot you can add one like the geolocation sensor: https://www.w3.org/TR/geolocation-sensor/#idl-index

```webidl
[SecureContext, Exposed=Window, Constructor(IdleDetectorOptions options)
interface IdleDetector : EventTarget {
  static Promise<IdleReading> read(optional ReadOptions readOptions);
  readonly attribute DOMHighResTimeStamp? timestamp;
  readonly attribute IdleState state;
  void start();
  void stop();
  attribute EventHandler onchange;
};

dictionary IdleDetectorOptions {
  double threshold;
};

dictionary ReadOptions : IdleDetectorOptions {
  AbortSignal? signal;
};

enum IdleState {
  "active",
  "idle",
  "locked" 
}

ictionary IdleReading {
  DOMHighResTimeStamp? timestamp;
  readonly attribute IdleState state;
```

**Comment by tomayac** [comment]
From @samuelgoto's [Explainer](https://github.com/samuelgoto/idle-detection/blob/master/README.md):

> locked - the system has an active screen lock preventing interaction with the user agent

As @kenchris said above, this should indeed be aligned with Wake Lock terms. A type [`"screen"` Wake Lock](https://w3c.github.io/wake-lock/#wake-locks) might still mean the user is idle (or rather: in DND mode, e.g., when presenting or watching a movie). If we think of idle detection [use cases](https://github.com/samuelgoto/idle-detection/blob/master/README.md#use-cases), a chat app should probably report "idle" if a screen lock is active (even if it's not the right word) in that case.

**Comment by samuelgoto** [comment]
Ha, I love `IdleDetector` @kenchris  and thanks for pointing out the sensors API for precedence/inspiration @domenic !

Looking at the [Accelerometer](https://w3c.github.io/sensors/#feature-detection) for inspiration, here is what it looks like:

```
let accelerometer = new Accelerometer({ frequency: 10 });
accelerometer.addEventListener('error', event => {
    // Handle runtime errors.
});
accelerometer.addEventListener('reading', () => reloadOnShake(accelerometer));
accelerometer.start();
```

@kenchris curious: is there a specific reason why you chose a `onreading` callback `EventHandler` as opposed to using the `addEventListener()` method of the subclassing of `EventTarget`? For example, would something along these lines be more consistent with the `Accelerometer` design:

```
let idleDetector = new IdleDetector({ threshold: 60 });
idleDetector.addEventListener('reading', () => reloadOnShake(idleDetector));
idleDetector.start();
```

WDYT?

Putting aside this, I also really like the design for one-shot queries with a static async method. This works really well to me:

```
const reading = await IdleDetector.read({ threshold: 2 * 60 });
```

**Comment by samuelgoto** [comment]
@tomayac wrt

> If we think of idle detection use cases, a chat app should probably report "idle" if a screen lock is active (even if it's not the right word) in that case.

I think that's the original [intent/model](https://github.com/samuelgoto/idle-detection/blob/master/README.md#model) and the [implementation](https://chromium-review.googlesource.com/c/chromium/src/+/1446402).

The state is reported in two orthogonal/different dimensions, the `user` state (idle/active) and the `screen` state (locked/unlocked).

We [debated a bit](https://chromium-review.googlesource.com/c/chromium/src/+/1446402/20#message-8b9ad0937907d025e34d2ddac9b983ade73c8eb7) whether it would be useful to decouple in different APIs the `user` state from the `screen` state, and arrived at [bundling](https://chromium-review.googlesource.com/c/chromium/src/+/1446402/20#message-0748dcf10712e064944661e4515704d529157bdc) but [weekly held](https://chromium-review.googlesource.com/c/chromium/src/+/1446402/20#message-0f082aaf3523c4bab633f85c80c587832d77c44c).

Does that make sense and address your point?

**Comment by kenchris** [comment]
> @kenchris curious: is there a specific reason why you chose a `onreading` callback `EventHandler` as opposed to using the `addEventListener()` method of the subclassing of `EventTarget`?

Both are supported :-) in addition to the onreading property there is a "reading" event. That is how EventTarget usually works.

**Comment by kenchris** [comment]
> And we thought that making start() return a `Promise` would allow us to return all sorts of initialization errors. E.g.:

That was considered for Sensors as well. I don't remember the discussion but the conclusion was that it was better not to (there is already the error event, as errors can happen at any time). @tobie @anssiko do you remember?

**Comment by tobie** [comment]
Yes. We dropped those promises as mentioned here: https://github.com/w3c/sensors/issues/104#issuecomment-248316955.

At best, you had to duplicate your event handlers and then filter out error messages between the promise and the event handler.

At worst it pushed developers to rely only on rejected promises as an error handling strategy and miss a number of error classes.

**Comment by kenchris** [comment]
Related: https://github.com/w3c/sensors/issues/93

**Comment by anssiko** [comment]
(For more historical context, this was discussed at famous Lisbon F2F https://www.w3.org/2016/09/20-dap-minutes.html, but I think the issue pointed out by @tobie is the best summary. You know F2F minutes.)

**Comment by torgo** [comment]
Pink @kenchris - can we discuss next week?

**Comment by kenchris** [comment]
@torgo sure thing!

**Comment by samuelgoto** [comment]
I got a [CL](https://github.com/chromium/chromium/blob/master/third_party/blink/web_tests/external/wpt/idle-detection/interceptor.https.html) in that covers a lot of ground and aligns with what was discussed here.

I'll follow up with some more API design questions that came up while we were coding this up momentarily.

**Comment by jwheare** [comment]
Would a name like “presence detector” be more appropriate to a) avoid confusion with requestIdleCallback and b) communicate that you can detect an active state as well as an idle one?

**Comment by cynthia** [comment]
Just to clarify, progress "stalled" has no negative implications, we're still in-progress (or "stalled") with a new (hopefully more efficient) work mode and the dual state means that "we have provided all the technical feedback we could, we know you have acknowledged the feedback and are happy to look at the next iteration when you have something ready".

As for the last comment from @jwheare - we don't have strong opinions about the naming. @kenchris noted that it can be confused with proximity.

**Comment by cynthia** [comment]
Thanks a lot for all the patience, we don't have much more feedback on this so we'll close this as part of our new process. If there are significant changes in the design, please ask us to re-open.

Thanks again for bringing this to our attention.

**Comment by reillyeon** [comment]
I would like to ask the TAG to reopen this review as there is now a specification available: https://wicg.github.io/idle-detection

The API design is mostly unchanged from what has been discussed here previously. What has been added is a new `'idle-detection'` permission which is required to call `start()` on an `IdleDetector` instance.

**Comment by torgo** [comment]
Hi @reillyeon - one question on this: what is the trajectory for this spec after WICG? Is this intended to be a part of the DAS work? We couldn't find it on the charter. Has there been any thinking on where this ends up? Sorry if that's documented somewhere above and I've missed it.

**Comment by reillyeon** [comment]
I do not have a destination working group in mind for this incubation.

**Comment by cynthia** [comment]
Sorry this took so long. We discussed this in our F2F today, and the proposed changes look great to us! From the back of our head, this feels like it would belong in Webapps, but as long as it ends up somewhere we are happy.

Thanks for bringing this to our attention.
