### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by dandclark** [w3ctag/design-reviews#405]
こんにちはTAG!

I'm requesting a TAG review of:

  - Name: CSS Modules
  - Specification URL: pending
  - Explainer (containing user needs and example code)¹:  https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md 
  - GitHub issues (if you prefer feedback filed there): https://github.com/w3c/webcomponents/issues/759
  - Tests: pending
  - Primary contacts (and their relationship to the specification): @dandclark @samsebree @travisleithead @gregwhitworth @bocupp

Further details:

  - Relevant time constraints or deadlines: None, though we're ready to move forward with an implementation in Blink.
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). There are no new security/privacy concerns, as this proposal follows JavaScript/JSON modules with respect to the usage of fetch.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

Much of the discussion regarding this feature thus far has taken place on this issue thread, also linked above: https://github.com/w3c/webcomponents/issues/759

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [ x ] leave review feedback as a comment in this issue and @-notify @dandclark

--------------------------

_Please preview the issue and check that the links work before submitting._ In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document.

¹ For background, see our [explanation of how to write a good explainer](https://w3ctag.github.io/explainers).

**Comment by dbaron** [comment]
Should we be looking at https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md rather than https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/CSSModules/v1Explainer.md ?

**Comment by dandclark** [comment]
The documents are currently identical, but https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md should be treated as the primary version going forward.  I'll update the other one to point to it.  Apologies for the ambiguity.

**Comment by travisleithead** [comment]
Thanks for doing that! (Sorry, I forgot to put the in-document notice after I updated the readme page on github...)
________________________________

**Comment by dbaron** [comment]
I'm currently looking at this with @kenchris in a breakout at the TAG meeting.

I think we both think this looks pretty reasonable.

I'm a little concerned about bypassing handling of `@import` for now -- worried that people will be disturbed by this feature not working.  I'd note that at least some (maybe all?) browser CSS implementations use copy-on-write sharing for stylesheets that are `@import`ed multiple times (whose CSSOM representation start off as thin wrappers until they're accessed).  So that might argue for just continuing to use that model.  On the other hand, the desire to handle `@import`s in a way that allows the CSSOM to modify all the instances at once seems like a reasonable desire as well -- and it seems reasonable to do CSS modules such that `@import`s share the `CSSStyleSheet` objects, they're all part of the module graph, and any stylesheet that's part of the module graph just has a null parent style sheet even if it's actually imported in one or more places.  It's a slightly bigger change to the model, but it does have benefits.

It's not clear to me what the benefit of deferring the decision is.  Is there particular evidence you're waiting for to settle this?  If not, it seems like it might be better to hammer out the decision sooner rather than crippling part of the feature just because of failure to agree on which path to take.

**Comment by tomayac** [comment]
Could a concept similar to [Preload's `as` attribute](https://w3c.github.io/preload/#as-attribute) be a way out, so the import can be parsed accordingly?

```js
import styles from "styles.css" as style;
```

Or alternatively more specific naming?

```js
importCSS styles from "styles.css";
```

**Comment by annevk** [comment]
Maybe, this is probably not the place to do design work. I mainly wanted to highlight the security issue so the TAG can take that into consideration when reviewing other work.

**Comment by dbaron** [comment]
@plinss and I are discussing this again in a breakout in [Cupertino](https://w3ctag.github.io/meetings/2019/12-cupertino/).

We'd note that there are additional variants of options 2 and 3 that could be considered, in particular:
* an option 2a that treats a failed `@import` as just something that gets dropped like in the rest of CSS, rather than causing the module to fail
* an option 3a that makes the CSSOM for such stylesheets readonly (although neither of us really like that)

Along those lines, it might be useful if the explainer says what happens when an `import` fails, for readers who aren't familiar enough with ES modules.  (I'm not!)

We're also concerned about relying on either the file extension (given that web behavior shouldn't depend on them) or the mime type (given the security issue mentioned above) to determine that it should be CSS, so it seems like there should be some syntax differentiation for stylesheet imports.

We're curious what the status of this is, and whether you have any thoughts on this or the previous comments?

**Comment by plinss** [comment]
I presume this also works with dynamic imports? In that case is the module returned simply the CSSStyleSheet?

**Comment by kenchris** [comment]
This seems relevant to the discussion: https://github.com/littledan/proposal-module-attributes/

**Comment by dandclark** [comment]
Re: @dbaron 

I agree that 2a is worth considering.  I am a little wary of not failing the module graph if any resource is not found, as that somewhat goes against the expectation that if a module graph is executing, all statically imported resources are present.  On the other hand the basic principle of option 2 is that we're not really changing the semantics of `@import` so perhaps just benignly dropping the missing `@import` to be consistent with the current CSS behavior makes sense.  I'll update the explainer to list this possibility as well.

I'm not sure that making the stylesheet OM read-only solves a lot of the issues with option 3; we still have the problem where a stylesheet can have multiple parents if `@import`ed from multiple sheets, and we would still need to decide the right way to reflect that in a read-only OM.  Furthermore, the main motivating scenario for option 3 is that dynamic changes to a particular stylesheet can be reflected in multiple importers.  If the OM is read-only this capability would be limited.

I'll add a comment in the explainer about the behavior when `import` fails (the module graph doesn't execute; same as with the failed `import` of a JavaScript module).

Your concerns about relying on file extension or MIME type are widely shared at this point.  Issue thread [here](https://github.com/w3c/webcomponents/issues/839).  We're proposing @littledan and @xtuc's https://github.com/littledan/proposal-module-attributes/ for State 1 to TC39 this week.  The ideal outcome is that this will enable us to use the `import` syntax to specify the module type, e.g.

```JavaScript
import styleSheet from "./foo.css" with type: "css";
```

Re @plinss:
> I presume this also works with dynamic imports? In that case is the module returned simply the CSSStyleSheet?

Yes, it will work with dynamic imports.  The returned Promise resolves with the module namespace object, where the `default` property is the CSSStyleSheet.  More discussion on this [here](https://github.com/w3c/webcomponents/issues/835).  That thread is about JSON modules but the ideas are the same.  Justin's comment [here](https://github.com/w3c/webcomponents/issues/835#issuecomment-529732659) notes that this keeps open the future possibility of things like exporting named CSS selector references.

**Comment by dbaron** [comment]
OK, it's good to hear that you're considering that feedback.  I don't think the TAG intends to be particularly pushy about this feedback, but we're happy to hear you're looking into it.

(The one note about the 3a readonly option is it's reflecting that many (maybe even all?) implementations use shared stylesheet inners and copy-on-write cloning when stylesheets are linked from multiple places.)

I think (although I don't want to speak for others on the TAG) that we can probably consider closing this issue at some point soon, since I'm not aware of additional feedback that we're expecting to provide.

**Comment by cynthia** [comment]
>  The ideal outcome is that this will enable us to use the import syntax to specify the module type

Given that the plumbing is in place, would this be mandated? If not, what is the intended behavior without the directive, given the file swap security concerns noted above?

**Comment by dbaron** [comment]
We (me, @plinss, @sangwhan, @ylafon) are looking at this again at our Wellington Face-to-Face.  We're still concerned about this `@import` issue getting punted.  It feels like the mechanisms for adding `@import` rules in dynamic situations already exist in the platform, though they may not be specified clearly; we just  filed w3c/csswg-drafts#4821 on that.

We'd like to continue to leave this open to monitor what's going on with handling of `@import` rules.

**Comment by dbaron** [comment]
Worth noting that the other related issue (not directly mentioned) was w3c/webcomponents#870.

**Comment by plinss** [comment]
We're happy with the direction this is taking, will continue to monitor the open issues.
