### ISSUE TITLE
HTML Horizontal Review: the <img> element

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#500]
This is a subtask of #499. Please review these three HTML PRs.

- [x] [Make `<img>.complete` more reliable](https://github.com/whatwg/html/pull/4934)
- [x] [Remove `<img>` progress events](https://github.com/whatwg/html/pull/4842)
- [x] [Use width and height as intrinsic aspect ratio for img elements](https://github.com/whatwg/html/pull/4952)

**Comment by hober** [comment]
We took a look at these three PRs in a breakout today. @atanassov had some thoughts about whatwg/html#4952 which I hope he'll capture in a comment here. Otherwise, we had no concerns.

**Comment by annevk** [comment]
FWIW, it would probably be better to file a new issue. Comments in closed issues or merged PRs tend to get forgotten.
