### ISSUE TITLE
HTML Horizontal Review: Windows, navigation, agents and agent clusters

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#502]
This is a subtask of #499. Please review these three HTML PRs:

- [x] [Imperatively allocate window agents and agent clusters](https://github.com/whatwg/html/pull/4617)
- [x] [Change default value of `window.open()`'s `url` argument](https://github.com/whatwg/html/pull/4851)
- [x] [Make window.window/frames/self deal with no browsing context](https://github.com/whatwg/html/pull/4410))

**Comment by hober** [comment]
I went ahead and checked off whatwg/html#4410 and whatwg/html#4851. They're both slight tweaks that bring the spec into alignment with implementations.

**Comment by hober** [comment]
We reviewed whatwg/html#4617 on today's call. We're happy to see the relationships between various ECMAScript and HTML concepts be tightened up. @dbaron wondered if this change reduced the number of degrees of freedom implementations have in choosing process models, but is confident that this received sufficient review at the time. Closing.

**Comment by annevk** [comment]
https://tc39.es/ecma262/#sec-forward-progress is the fundamental constraint. This affects dedicated workers and shared workers as specified (they have [[CanBlock]] set to true, though in implementations this might only be true for dedicated workers at the moment). Everything else can in theory run on the same thread, though on CPU architectures impacted by Spectre this would be ill-advised. Hope that helps.
