### ISSUE TITLE
HTML Horizontal Review: Documents, DocumentOrShadowRoot, etc.

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#503]
This is a subtask of #499. Please review these three HTML PRs:

- [x] [Define `DocumentOrShadowRoot`'s `activeElement`](https://github.com/whatwg/html/pull/4837)
- [x] [Ignore document.open/write after the active parser has been aborted](https://github.com/whatwg/html/pull/4907)
- [x] [Define `getSVGDocument()` in terms of content document](https://github.com/whatwg/html/pull/5109)
