### ISSUE TITLE
HTML Horizontal Review: Event Loop, task queues, etc.

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#504]
This is a subtask of #499. Please review these three HTML PRs:

- [x] [Specify which event loop to use for posting messages](https://github.com/whatwg/html/pull/4917)
- [x] [Add "queue an element task” algorithm](https://github.com/whatwg/html/pull/5072)
- [x] [Introduce `SubmitEvent` for the form `submit` event](https://github.com/whatwg/html/pull/4984)

**Comment by kenchris** [comment]
This all looks good to us!
