### ISSUE TITLE
HTML Horizontal Review: misc / reorg / cleanup

### ISSUE THREAD

**Issue by hober** [w3ctag/design-reviews#505]
This is a subtask of #499. Please review these three HTML PRs:

- [x] [Update all constructors, including `HTMLConstructor`](https://github.com/whatwg/html/pull/4915)
- [x] [Move the `DOMParser` class to HTML](https://github.com/whatwg/html/pull/5190)
- [x] [Cleanups to "execute a script block” Signpost the debate on some script mismatches](https://github.com/whatwg/html/pull/5154)

**Comment by hober** [comment]
We looked at these three changes in a breakout today, and we don't think there's anything of concern here.
